const menuItems = [
  {
    name: 'Margherita Pizza',
    description: 'Classic pizza with fresh mozzarella, tomato sauce, and basil',
    price: 12.99,
    category: 'main-course',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
    isAvailable: true,
    preparationTime: 20,
    ingredients: ['Dough', 'Tomato Sauce', 'Mozzarella', 'Basil', 'Olive Oil'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: {
      calories: 250,
      protein: 12,
      carbs: 35,
      fat: 8,
    },
    customizationOptions: [
      {
        name: 'Size',
        choices: ['Small', 'Medium', 'Large'],
        required: true,
      },
      {
        name: 'Extra Toppings',
        choices: ['Mushrooms', 'Olives', 'Pepperoni', 'Extra Cheese'],
        required: false,
      },
    ],
  },
  {
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce with parmesan, croutons, and Caesar dressing',
    price: 8.99,
    category: 'appetizer',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
    isAvailable: true,
    preparationTime: 10,
    ingredients: ['Romaine Lettuce', 'Parmesan', 'Croutons', 'Caesar Dressing'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    nutritionalInfo: {
      calories: 180,
      protein: 8,
      carbs: 15,
      fat: 10,
    },
  },
  {
    name: 'Grilled Chicken Burger',
    description: 'Juicy grilled chicken breast with lettuce, tomato, and special sauce',
    price: 11.99,
    category: 'main-course',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    isAvailable: true,
    preparationTime: 25,
    ingredients: ['Chicken Breast', 'Burger Bun', 'Lettuce', 'Tomato', 'Special Sauce'],
    allergens: ['Gluten', 'Eggs'],
    nutritionalInfo: {
      calories: 450,
      protein: 35,
      carbs: 40,
      fat: 15,
    },
    customizationOptions: [
      {
        name: 'Cheese',
        choices: ['No Cheese', 'Cheddar', 'Swiss', 'Pepper Jack'],
        required: false,
      },
    ],
  },
  {
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with a gooey molten center, served with vanilla ice cream',
    price: 6.99,
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400',
    isAvailable: true,
    preparationTime: 15,
    ingredients: ['Chocolate', 'Flour', 'Butter', 'Eggs', 'Sugar', 'Vanilla Ice Cream'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    nutritionalInfo: {
      calories: 380,
      protein: 5,
      carbs: 48,
      fat: 20,
    },
  },
  {
    name: 'Fresh Lemonade',
    description: 'Freshly squeezed lemonade with a hint of mint',
    price: 3.99,
    category: 'beverage',
    image: 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9f?w=400',
    isAvailable: true,
    preparationTime: 5,
    ingredients: ['Lemons', 'Water', 'Sugar', 'Mint'],
    allergens: [],
    nutritionalInfo: {
      calories: 120,
      protein: 0,
      carbs: 30,
      fat: 0,
    },
    customizationOptions: [
      {
        name: 'Ice',
        choices: ['No Ice', 'Regular Ice', 'Extra Ice'],
        required: true,
      },
    ],
  },
  {
    name: 'Garlic Bread',
    description: 'Toasted bread with garlic butter and herbs',
    price: 4.99,
    category: 'sides',
    image: 'https://images.unsplash.com/photo-1573140401552-3fab0b24f494?w=400',
    isAvailable: true,
    preparationTime: 10,
    ingredients: ['Bread', 'Garlic', 'Butter', 'Parsley'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: {
      calories: 200,
      protein: 4,
      carbs: 25,
      fat: 9,
    },
  },
  {
    name: 'Spaghetti Carbonara',
    description: 'Creamy pasta with bacon, eggs, and parmesan cheese',
    price: 13.99,
    category: 'main-course',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400',
    isAvailable: true,
    preparationTime: 20,
    ingredients: ['Spaghetti', 'Bacon', 'Eggs', 'Parmesan', 'Black Pepper'],
    allergens: ['Gluten', 'Dairy', 'Eggs'],
    nutritionalInfo: {
      calories: 520,
      protein: 22,
      carbs: 55,
      fat: 22,
    },
  },
  {
    name: 'Mozzarella Sticks',
    description: 'Crispy fried mozzarella served with marinara sauce',
    price: 7.99,
    category: 'appetizer',
    image: 'https://images.unsplash.com/photo-1531749668029-2db88e4276c7?w=400',
    isAvailable: true,
    preparationTime: 12,
    ingredients: ['Mozzarella', 'Breadcrumbs', 'Marinara Sauce'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: {
      calories: 320,
      protein: 15,
      carbs: 28,
      fat: 16,
    },
  },
];

module.exports = { menuItems };